# Generated by Django 3.0.3 on 2020-02-05 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('Name', 'Name'), ('Link', 'Link'), ('Phone', 'Phone'), ('Email', 'Email'), ('Postmail', 'Postmail'), ('Education', 'Education'), ('Professional Experience', 'Professional Experiance'), ('Project Work', 'Project Work'), ('Publications', 'Publications'), ('Courses', 'Courses'), ('Technical Skills', 'Technical Skills'), ('Extra Curricular', 'Extra Curricular')], max_length=128)),
                ('body', models.TextField()),
                ('formatting', models.CharField(choices=[('org-loc-title-date-points', 'Org Loc Title Date Points'), ('date-points', 'Date Points'), ('text', 'Text')], default='text', max_length=128)),
                ('created', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.User')),
            ],
        ),
    ]
